using System.IO;
using System.Reflection;
using AwesomeAssertions;
using LuaToolsGui.ViewModels;
using Xunit;

namespace LuaToolsGui.Tests;

/// <summary>
/// The AmethystTool card after it moved from the Plugin page to the Mode page, checked from both ends: the
/// names ModeView.xaml binds to, and the members the view models expose.
///
/// <para>
/// Same reason as <see cref="ModeUninstallBindingTests"/> — WPF bindings fail SILENTLY, and a move is
/// exactly where they break: every path in the card was rewritten to reach the page through
/// <c>ElementName=Root</c> instead of its own view model, and half the members on the other end are
/// generated by the MVVM source generator from a backing field, so a rename breaks the pair without
/// breaking the compile.
/// </para>
///
/// <para>
/// The other half of the move is that the card must be <b>gone</b> from the Plugin page. A copy left behind
/// there would still compile, still bind, and still install — giving two buttons that fight over the same
/// four files next to steam.exe.
/// </para>
/// </summary>
public class AmethystToolModeBindingTests
{
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "LuaToolsGui.sln")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new DirectoryNotFoundException("LuaToolsGui.sln not found above the test output.");
    }

    private static string View(string name) =>
        File.ReadAllText(Path.Combine(RepoRoot(), "src", "LuaToolsGui", "Views", name));

    private static string ModeViewXaml() => View("ModeView.xaml");
    private static string PluginViewXaml() => View("PluginView.xaml");

    private static bool HasPublicMember(Type type, string name) =>
        type.GetProperty(name, BindingFlags.Public | BindingFlags.Instance) is not null;

    /// <summary>Just the AmethystTool card's markup — from its DataContext down to its closing Border.</summary>
    private static string AmethystCardMarkup()
    {
        string xaml = ModeViewXaml();
        int start = xaml.IndexOf("DataContext=\"{Binding Amethyst}\"", StringComparison.Ordinal);
        start.Should().BeGreaterThan(-1);
        return xaml[start..];
    }

    // ── The page-level members the card reaches through ElementName=Root ──

    [Theory]
    [InlineData("InstallAmethystCommand")]
    [InlineData("UninstallAmethystCommand")]
    [InlineData("CanUninstallAmethyst")]
    [InlineData("Amethyst")]
    public void The_page_exposes_what_the_card_binds(string member)
    {
        ModeViewXaml().Should().Contain(member);
        HasPublicMember(typeof(ModeViewModel), member).Should().BeTrue();
    }

    // ── The members the card's own DataContext supplies ──

    [Theory]
    [InlineData("IsInstalled")]
    [InlineData("IsActive")]
    [InlineData("UpdateAvailable")]
    [InlineData("Status")]
    [InlineData("InstalledVersion")]
    [InlineData("LatestVersion")]
    [InlineData("ShowNoRecordHint")]
    [InlineData("StatusLine")]
    [InlineData("BackupLine")]
    [InlineData("InstallButtonText")]
    [InlineData("InstallIsPrimary")]
    public void The_card_exposes_what_its_markup_binds(string member)
    {
        ModeViewXaml().Should().Contain(member);
        HasPublicMember(typeof(AmethystToolViewModel), member).Should().BeTrue();
    }

    [Fact]
    public void The_card_is_bound_through_the_pages_Amethyst_property()
    {
        ModeViewXaml().Should().Contain("DataContext=\"{Binding Amethyst}\"");
    }

    // ── The move, not just the arrival ──

    [Fact]
    public void The_card_no_longer_exists_on_the_Plugin_page()
    {
        // Two install buttons for one set of four files is worse than none.
        PluginViewXaml().Should().NotContain("Amethyst");
    }

    [Fact]
    public void The_Plugin_page_no_longer_hosts_the_card_view_model()
    {
        HasPublicMember(typeof(PluginViewModel), "Amethyst").Should().BeFalse();

        // The constructor is the other half: leaving the parameter would keep the DI edge alive and the
        // page would still be resolving a view model nothing on it renders.
        typeof(PluginViewModel).GetConstructors()
            .SelectMany(c => c.GetParameters())
            .Should().NotContain(p => p.ParameterType == typeof(AmethystToolViewModel));
    }

    [Fact]
    public void The_page_owns_the_confirmation_the_card_used_to_raise_itself()
    {
        // The card used to put up two MessageBox prompts of its own. On this page the Mode cards confirm
        // through the in-page overlay, and the card now goes through the same one — which is also what
        // holds the page busy for the whole operation, so a Mode install cannot start on top of it.
        var vm = typeof(AmethystToolViewModel);

        vm.GetMethod("InstallConfirmedAsync", BindingFlags.Public | BindingFlags.Instance)
            .Should().NotBeNull("the page confirms, then calls this");
        vm.GetMethod("UninstallConfirmedAsync", BindingFlags.Public | BindingFlags.Instance)
            .Should().NotBeNull();

        // The command pair the card used to expose is gone; ModeViewModel drives it now.
        HasPublicMember(vm, "InstallCommand").Should().BeFalse();
        HasPublicMember(vm, "UninstallCommand").Should().BeFalse();
    }

    // ── One backend active at a time ──────────────────────────────────────────

    [Fact]
    public void The_ACTIVE_badge_is_bound_to_IsActive_and_not_to_file_presence()
    {
        // The bug this replaces: the badge was bound to IsInstalled, which is pure file presence. A Mode
        // install overwrites dwmapi.dll and xinput1_4.dll but leaves AmethystTool.dll and amethysttool.toml
        // alone, so the files stayed "installed" after the slot moved on — and the page lit ACTIVE twice.
        string badge = AmethystCardMarkup();
        int active = badge.IndexOf("Strings.Mode_Active", StringComparison.Ordinal);
        active.Should().BeGreaterThan(-1, "the card shows the same ACTIVE badge the Mode cards do");

        // The Visibility binding sits just above the badge's TextBlock.
        string upToBadge = badge[..active];
        upToBadge.Should().Contain("Visibility=\"{Binding IsActive,");
        upToBadge.Should().NotContain("Visibility=\"{Binding IsInstalled,");
    }

    [Fact]
    public void AmethystTool_is_the_first_card_on_the_page()
    {
        // The Mode cards render from an ItemsControl; this one is markup of its own, so its position in
        // the file IS its position on the page.
        string xaml = ModeViewXaml();
        int amethyst = xaml.IndexOf("DataContext=\"{Binding Amethyst}\"", StringComparison.Ordinal);
        int cards = xaml.IndexOf("ItemsSource=\"{Binding Cards}\"", StringComparison.Ordinal);

        amethyst.Should().BeGreaterThan(-1);
        cards.Should().BeGreaterThan(-1);
        amethyst.Should().BeLessThan(cards, "AmethystTool leads the Mode list");
    }

    [Fact]
    public void The_view_model_can_report_active_and_installed_separately()
    {
        // Two distinct flags, so a Mode taking the slot demotes the badge without pretending the payload
        // files vanished — Uninstall still has something to remove.
        var vm = new AmethystToolViewModel(null!, null!) { IsInstalled = true, IsActive = false };

        vm.IsInstalled.Should().BeTrue();
        vm.IsActive.Should().BeFalse();
    }

    [Fact]
    public void The_card_draws_no_progress_bar_of_its_own()
    {
        // The page has one docked at the bottom, shared by every Mode. ModeViewModel mirrors the card's
        // progress into it, so a second bar inside the card would be a duplicate that tracks the same work.
        var cardStart = ModeViewXaml().IndexOf("DataContext=\"{Binding Amethyst}\"", StringComparison.Ordinal);
        cardStart.Should().BeGreaterThan(-1);

        string card = ModeViewXaml()[cardStart..];
        int cardEnd = card.IndexOf("</Border>", StringComparison.Ordinal);
        card[..cardEnd].Should().NotContain("<ProgressBar");
    }
}
