using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using AwesomeAssertions;
using LuaToolsGui.ViewModels;
using Xunit;

namespace LuaToolsGui.Tests;

/// <summary>
/// The Home dashboard, checked from both ends: the names <c>HomeView.xaml</c> binds to, and the members
/// <see cref="HomeViewModel"/> exposes.
///
/// <para>
/// Same reason as <see cref="AmethystToolModeBindingTests"/> — a WPF binding to a member that does not
/// exist fails SILENTLY, leaving a blank line where a status used to be. Half the members on the other end
/// are generated by the MVVM source generator from a backing field or a method name, so a rename breaks the
/// pair without breaking the compile.
/// </para>
///
/// <para>
/// The page cannot be constructed here to check this the direct way: it takes ten services, several of
/// which touch the Steam folder and GitHub. Reflection over the type answers the same question — does the
/// name exist — without standing up the DI graph.
/// </para>
/// </summary>
public class HomeDashboardBindingTests
{
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "LuaToolsGui.sln")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new DirectoryNotFoundException("LuaToolsGui.sln not found above the test output.");
    }

    private static string HomeViewXaml() =>
        File.ReadAllText(Path.Combine(RepoRoot(), "src", "LuaToolsGui", "Views", "HomeView.xaml"));

    private static bool HasPublicMember(string name) =>
        typeof(HomeViewModel).GetProperty(name, BindingFlags.Public | BindingFlags.Instance) is not null;

    // ── The members the dashboard reports state through ───────────────────────

    [Theory]
    [InlineData("SteamRunning")]      // Steam is up right now — not merely installed somewhere
    [InlineData("SteamRunningText")]
    [InlineData("ModeStatus")]        // whichever backend holds the proxy-DLL slot
    [InlineData("HasActiveBackend")]
    [InlineData("VersionLabel")]
    [InlineData("SelfUpdateDisabled")]
    [InlineData("PrivacyText")]
    public void The_status_members_the_page_binds_to_exist(string member) =>
        HasPublicMember(member).Should().BeTrue($"HomeView.xaml binds {member}, and a missing one binds to nothing");

    [Theory]
    [InlineData("OpenModeCommand")]
    [InlineData("OpenPluginCommand")]
    [InlineData("OpenSettingsCommand")]
    [InlineData("OpenAboutCommand")]      // privacy row + the "Updates" quick action
    [InlineData("RefreshStatusCommand")]  // generated from RefreshStatusAsync — the Async suffix is dropped
    public void The_commands_the_page_binds_to_exist(string command) =>
        HasPublicMember(command).Should().BeTrue($"HomeView.xaml binds {command}, and a missing one is a dead button");

    /// <summary>
    /// Every <c>{Binding X}</c> path in the page resolves to a member of the view model.
    ///
    /// <para>
    /// Paths that reach somewhere else are excluded by shape, not by name: the recent-card template binds
    /// against <see cref="LuaTileViewModel"/>, the drop zone against its own view model through an explicit
    /// <c>DataContext</c>, and one binding goes through <c>ElementName=Root</c>. Those have their own
    /// coverage; this checks the ones whose data context IS the Home view model.
    /// </para>
    /// </summary>
    [Fact]
    public void Every_simple_binding_path_on_the_page_resolves_to_a_member()
    {
        string xaml = HomeViewXaml();

        // Anything qualified (DataContext.X), indexed, or carrying a source (ElementName=, Converter=) is
        // another data context's problem. A bare "{Binding Name}" or "{Binding Name, Mode=…}" is ours.
        var paths = Regex.Matches(xaml, @"\{Binding\s+(?<path>[A-Za-z_][A-Za-z0-9_]*)\s*(?<tail>[},])")
            .Select(m => (path: m.Groups["path"].Value, tail: m.Groups["tail"].Value))
            .Select(x => x.path)
            .Distinct(StringComparer.Ordinal)
            .ToList();

        // Members of the tile/drop view models that legitimately appear on this page.
        var elsewhere = new HashSet<string>(StringComparer.Ordinal) { "Cover", "Name" };

        var missing = paths
            .Where(p => !elsewhere.Contains(p))
            .Where(p => !HasPublicMember(p))
            .ToList();

        missing.Should().BeEmpty("HomeView.xaml binds names the Home view model does not expose");
    }

    // ── i18n: nothing on this page may be a compiled-in English literal ───────

    /// <summary>
    /// No visible string is written into the markup. Every one goes through
    /// <c>{x:Static res:Strings.…}</c> or a binding, so a translated build has no English island on the
    /// first page the user sees — which is exactly what happened to the nav rail's Plugin entry.
    /// </summary>
    [Theory]
    [InlineData("Text")]
    [InlineData("Content")]
    [InlineData("ToolTip")]
    public void No_user_visible_string_is_hardcoded_in_the_markup(string attribute)
    {
        string xaml = HomeViewXaml();

        var literals = Regex.Matches(xaml, $@"\b{attribute}=""(?<value>[^""]*)""")
            .Select(m => m.Groups["value"].Value)
            .Where(v => v.Length > 0)
            .Where(v => !v.StartsWith('{'))          // binding or markup extension — not a literal
            .Distinct(StringComparer.Ordinal)
            .ToList();

        literals.Should().BeEmpty(
            $@"a hardcoded {attribute}=""…"" on the Home page shows in English no matter the language");
    }

    // ── The state the page must be able to show ──────────────────────────────

    /// <summary>
    /// Steam's running state is reported in WORDS, not by colour alone.
    ///
    /// <para>
    /// The row paints a success tint when Steam is up. Colour on its own is not an accessible signal, so
    /// the badge carries the text too — and the text is what a screen reader gets.
    /// </para>
    /// </summary>
    [Fact]
    public void The_steam_badge_states_its_meaning_in_text_not_only_in_colour()
    {
        HomeViewXaml().Should().Contain("{Binding SteamRunningText}");
        Resources.Strings.Home_SteamRunning.Should().NotBeNullOrWhiteSpace();
        Resources.Strings.Home_SteamClosed.Should().NotBeNullOrWhiteSpace();
        Resources.Strings.Home_SteamRunning.Should().NotBe(Resources.Strings.Home_SteamClosed);
    }

    /// <summary>
    /// The custom-templated buttons show keyboard focus.
    ///
    /// <para>
    /// Both tile styles replace the control template outright, which drops the chrome that would otherwise
    /// carry a focus visual; WPF's dotted adorner is close to invisible on these surfaces. Without an
    /// explicit trigger, tabbing through the dashboard moves an invisible cursor.
    /// </para>
    /// </summary>
    [Fact]
    public void Both_custom_button_templates_show_where_the_keyboard_is()
    {
        string xaml = HomeViewXaml();

        Regex.Matches(xaml, @"IsKeyboardFocused"" Value=""True""").Count
            .Should().BeGreaterThanOrEqualTo(2,
                "CardTileButton and StatusRowButton each replace the template, so each needs its own focus trigger");
    }

    /// <summary>
    /// Home reports the active backend through AmethystTool as well as through the Modes.
    ///
    /// <para>
    /// This is the regression the row was rewritten for: it used to read <c>SelectedModeDisplayName</c>
    /// alone, which is null while AmethystTool holds the slot (see <see cref="LuaToolsGui.Services.ActiveBackendPolicy"/>),
    /// so the dashboard told every AmethystTool user "no mode selected". There is one slot, so there is one
    /// question — and the answer has three cases, not two.
    /// </para>
    /// </summary>
    [Fact]
    public void The_backend_row_has_a_distinct_wording_for_each_of_its_three_states()
    {
        var states = new[]
        {
            Resources.Strings.Home_NoModeSelected,
            Resources.Strings.Home_ModeIs,
            Resources.Strings.Home_AmethystActive,
        };

        states.Should().OnlyHaveUniqueItems();
        states.Should().OnlyContain(s => !string.IsNullOrWhiteSpace(s));
        Resources.Strings.Home_ModeIs.Should().Contain("{0}", "the mode's display name is substituted in");
    }
}
