using System.IO;
using System.Reflection;
using AwesomeAssertions;
using LuaToolsGui.ViewModels;
using Xunit;

namespace LuaToolsGui.Tests;

/// <summary>
/// The Mode page's Uninstall controls, checked from both ends: the names ModeView.xaml binds to, and the
/// members the view models actually expose.
///
/// <para>
/// WPF bindings fail SILENTLY. A misspelt path renders a button that is permanently disabled, or a hint
/// that never appears, with nothing in the build output and nothing on screen to say why — and half of
/// these members are generated by the MVVM source generator from a backing field, so a rename in either
/// direction breaks the pair without breaking the compile.
/// </para>
/// </summary>
public class ModeUninstallBindingTests
{
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "LuaToolsGui.sln")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new DirectoryNotFoundException("LuaToolsGui.sln not found above the test output.");
    }

    private static string ModeViewXaml() =>
        File.ReadAllText(Path.Combine(RepoRoot(), "src", "LuaToolsGui", "Views", "ModeView.xaml"));

    private static bool HasPublicMember(Type type, string name) =>
        type.GetProperty(name, BindingFlags.Public | BindingFlags.Instance) is not null;

    // ── The page-level members the card template reaches through DataContext ──

    [Theory]
    [InlineData("UninstallModeCommand")]
    [InlineData("CanUninstallMode")]
    [InlineData("ConfirmCommand")]
    [InlineData("ConfirmBody")]
    [InlineData("ConfirmTitle")]
    public void The_page_exposes_what_the_view_binds(string member)
    {
        ModeViewXaml().Should().Contain(member);
        HasPublicMember(typeof(ModeViewModel), member).Should().BeTrue();
    }

    [Theory]
    [InlineData("ShowUninstall")]
    [InlineData("ShowNoRecordHint")]
    public void The_card_exposes_what_its_template_binds(string member)
    {
        ModeViewXaml().Should().Contain(member);
        HasPublicMember(typeof(ModeCardViewModel), member).Should().BeTrue();
    }

    [Fact]
    public void The_old_install_only_confirm_command_is_gone_from_both_sides()
    {
        // One overlay now serves install and uninstall. A leftover ConfirmInstallCommand binding would
        // render a primary button that does nothing at all.
        ModeViewXaml().Should().NotContain("ConfirmInstallCommand");
        HasPublicMember(typeof(ModeViewModel), "ConfirmInstallCommand").Should().BeFalse();
    }

    // ── What the button and hint are gated on ─────────────────────────────────

    [Fact]
    public void Uninstall_appears_on_the_active_mode()
    {
        var vm = new ModeCardViewModel(LuaToolsGui.Models.UnlockerMode.SteamTools, "SteamTools", "desc");

        vm.IsActive = true;
        vm.ShowUninstall.Should().BeTrue();
    }

    [Fact]
    public void Uninstall_does_not_appear_on_a_mode_that_is_not_active()
    {
        var vm = new ModeCardViewModel(LuaToolsGui.Models.UnlockerMode.SteamTools, "SteamTools", "desc")
        {
            HasInstallRecord = true,
        };

        vm.ShowUninstall.Should().BeFalse();
        vm.ShowNoRecordHint.Should().BeFalse();
    }

    [Fact]
    public void The_no_record_hint_shows_only_on_the_active_card_that_has_no_record()
    {
        var vm = new ModeCardViewModel(LuaToolsGui.Models.UnlockerMode.SteamTools, "SteamTools", "desc")
        {
            IsActive = true,
        };

        vm.ShowNoRecordHint.Should().BeTrue("an active mode with nothing recorded needs the reason, not a dead button");

        vm.HasInstallRecord = true;
        vm.ShowNoRecordHint.Should().BeFalse();
    }
}
