using System.IO;
using System.Linq;
using System.Reflection;
using AwesomeAssertions;
using LuaToolsGui.Services;
using LuaToolsGui.ViewModels;
using Xunit;

namespace LuaToolsGui.Tests;

/// <summary>
/// The Plugin page's source controls, checked from both ends: the names PluginView.xaml binds to, and the
/// members the view models actually expose.
///
/// <para>
/// Same reasoning as <see cref="ModeUninstallBindingTests"/>, and the same failure it guards against: WPF
/// bindings fail SILENTLY. A misspelt path renders a card whose "Use this source" button is permanently
/// invisible, or a status line that is permanently blank, with nothing in the build output and nothing on
/// screen to say why. Most of these members are generated by the MVVM source generator from a backing
/// field, so a rename in either direction breaks the pair without breaking the compile.
/// </para>
///
/// <para>
/// This matters more on this page than on most. The card bindings are what tell the user WHICH creator's
/// build is active and what is wrong with the one they are not on — and since nothing falls back any more,
/// a silently dead binding here leaves them unable to see, or to act on, a stuck plugin.
/// </para>
/// </summary>
public class PluginSourceBindingTests
{
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "LuaToolsGui.sln")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new DirectoryNotFoundException("LuaToolsGui.sln not found above the test output.");
    }

    private static string PluginViewXaml() =>
        File.ReadAllText(Path.Combine(RepoRoot(), "src", "LuaToolsGui", "Views", "PluginView.xaml"));

    private static bool HasPublicMember(Type type, string name) =>
        type.GetProperty(name, BindingFlags.Public | BindingFlags.Instance) is not null;

    // ── Page-level members, including the ones the card template reaches through DataContext ──

    [Theory]
    [InlineData("Sources")]
    [InlineData("ActiveSource")]
    [InlineData("ActiveSourceError")]
    [InlineData("ActivateCommand")]
    [InlineData("NotBusy")]
    public void The_page_exposes_what_the_view_binds(string member)
    {
        PluginViewXaml().Should().Contain(member);
        HasPublicMember(typeof(PluginViewModel), member).Should().BeTrue();
    }

    // ── Card-level members: the per-creator template ──

    [Theory]
    [InlineData("Slug")]
    [InlineData("Creator")]
    [InlineData("IsActive")]
    [InlineData("IsDefault")]
    [InlineData("LatestVersion")]
    [InlineData("StatusText")]
    [InlineData("ProblemText")]
    [InlineData("ShowActivate")]
    public void The_card_exposes_what_its_template_binds(string member)
    {
        PluginViewXaml().Should().Contain(member);
        HasPublicMember(typeof(PluginSourceCardViewModel), member).Should().BeTrue();
    }

    // ── The status row's four states ──────────────────────────────────────────

    [Theory]
    [InlineData("DllOk")]
    [InlineData("DllOutOfDate")]
    [InlineData("DllUnknown")]
    [InlineData("DllNotInstalled")]
    public void Every_loader_state_the_row_can_paint_is_bound_and_exposed(string member)
    {
        // The row stacks four icons in one cell and shows exactly one. A state the view-model can enter but
        // the view never draws leaves that cell EMPTY — no icon at all, which reads as a rendering bug
        // rather than as a status.
        PluginViewXaml().Should().Contain(member);
        HasPublicMember(typeof(PluginViewModel), member).Should().BeTrue();
    }

    [Fact]
    public void Each_loader_state_maps_to_exactly_one_of_the_bound_flags()
    {
        // Exclusivity is structural, not asserted: the four flags are set from one PluginLoaderState value,
        // so two cannot be true and none cannot be true. What is checked here is the pairing — that every
        // member of the enum has a flag the XAML actually draws. Adding a fifth state without a fifth icon
        // would leave that cell EMPTY, which reads as a rendering bug rather than as a status.
        var flagFor = new Dictionary<PluginLoaderState, string>
        {
            [PluginLoaderState.NotInstalled] = "DllNotInstalled",
            [PluginLoaderState.UpToDate] = "DllOk",
            [PluginLoaderState.OutOfDate] = "DllOutOfDate",
            [PluginLoaderState.Unverifiable] = "DllUnknown",
        };

        flagFor.Keys.Should().BeEquivalentTo(Enum.GetValues<PluginLoaderState>(),
            "every loader state the policy can return needs an icon on the row");
        flagFor.Values.Should().OnlyHaveUniqueItems("two states sharing a flag is two icons at once");
    }

    [Fact]
    public void The_up_to_date_pill_is_bound_and_owned_by_the_policy()
    {
        // The rule itself is covered by PluginLoaderPolicyTests. What this checks is that the page still
        // renders it and did not quietly go back to computing it from UpdateAvailable at the binding.
        PluginViewXaml().Should().Contain("ShowUpToDate");
        HasPublicMember(typeof(PluginViewModel), "ShowUpToDate").Should().BeTrue();
    }

    [Fact]
    public void The_switch_action_is_wired_to_the_page_command_with_the_card_as_its_argument()
    {
        string xaml = PluginViewXaml();

        // The command lives on the PAGE (it installs, and only the page owns IsBusy/progress) while the
        // card is what identifies WHICH source to install — so the parameter must be the card itself.
        // Dropping CommandParameter compiles and renders a button that switches to nothing.
        xaml.Should().Contain("DataContext.ActivateCommand");
        xaml.Should().Contain("CommandParameter=\"{Binding}\"");
    }
}
