//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed resource accessor for Strings.resx. Hand-maintained (not IDE-generated)
//     so it works under `dotnet watch` / CLI builds without the RESX custom tool.
//     Add a property here whenever you add a key to Strings.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuaToolsGui.Resources;

using System.Globalization;
using System.Resources;

public static class Strings
{
    private static readonly ResourceManager Rm =
        new("LuaToolsGui.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Look up a localized string by key for the current UI culture.</summary>
    public static string Get(string key) => Rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    // ── Navigation ──
    public static string Nav_Home => Get(nameof(Nav_Home));
    public static string Nav_Add => Get(nameof(Nav_Add));
    public static string Nav_Manage => Get(nameof(Nav_Manage));
    public static string Nav_Builds => Get(nameof(Nav_Builds));
    public static string Nav_Mode => Get(nameof(Nav_Mode));
    public static string Nav_Fixes => Get(nameof(Nav_Fixes));
    public static string Nav_RestartSteam => Get(nameof(Nav_RestartSteam));
    public static string Nav_Settings => Get(nameof(Nav_Settings));
    public static string Nav_Plugin => Get(nameof(Nav_Plugin));
    public static string Nav_SignInDiscord => Get(nameof(Nav_SignInDiscord));
    public static string Nav_WaitingForBrowser => Get(nameof(Nav_WaitingForBrowser));
    public static string Nav_Footer_Guest => Get(nameof(Nav_Footer_Guest));
    public static string Nav_Footer_LoggedIn => Get(nameof(Nav_Footer_LoggedIn));
    public static string Main_RestartSteam_Ask => Get(nameof(Main_RestartSteam_Ask));

    // ── Settings ──
    public static string Settings_Title => Get(nameof(Settings_Title));
    public static string Settings_Section_Account => Get(nameof(Settings_Section_Account));
    public static string Settings_Section_General => Get(nameof(Settings_Section_General));
    public static string Settings_Section_Steam => Get(nameof(Settings_Section_Steam));
    public static string Settings_Section_Install => Get(nameof(Settings_Section_Install));
    public static string Settings_SignOut => Get(nameof(Settings_SignOut));
    public static string Settings_BrowsingAsGuest => Get(nameof(Settings_BrowsingAsGuest));
    public static string Settings_GuestHint => Get(nameof(Settings_GuestHint));
    public static string Settings_SignInDiscord => Get(nameof(Settings_SignInDiscord));
    public static string Settings_BotCode_Hint => Get(nameof(Settings_BotCode_Hint));
    public static string Settings_BotCode_Placeholder => Get(nameof(Settings_BotCode_Placeholder));
    public static string Settings_BotCode_Redeem => Get(nameof(Settings_BotCode_Redeem));
    public static string Settings_BotCode_Expired => Get(nameof(Settings_BotCode_Expired));
    public static string Settings_BotCode_Invalid => Get(nameof(Settings_BotCode_Invalid));
    public static string Settings_BotCode_ServerError => Get(nameof(Settings_BotCode_ServerError));
    public static string Settings_BotLink_Title => Get(nameof(Settings_BotLink_Title));
    public static string Settings_BotLink_Body => Get(nameof(Settings_BotLink_Body));
    public static string Settings_BotLink_Dismiss => Get(nameof(Settings_BotLink_Dismiss));
    public static string Settings_LoginRequired => Get(nameof(Settings_LoginRequired));
    public static string Settings_ManageKeyHintPrefix => Get(nameof(Settings_ManageKeyHintPrefix));
    public static string Settings_Section_Hubcap => Get(nameof(Settings_Section_Hubcap));
    public static string Settings_HubcapKey => Get(nameof(Settings_HubcapKey));
    public static string Settings_HubcapKey_Hint => Get(nameof(Settings_HubcapKey_Hint));
    public static string Settings_HubcapKeyPlaceholder => Get(nameof(Settings_HubcapKeyPlaceholder));
    public static string Settings_HubcapValidate => Get(nameof(Settings_HubcapValidate));
    public static string Settings_HubcapClear => Get(nameof(Settings_HubcapClear));
    public static string Settings_HubcapGetKey => Get(nameof(Settings_HubcapGetKey));
    public static string Settings_HubcapKeyOk => Get(nameof(Settings_HubcapKeyOk));
    public static string Settings_HubcapKeyOkExpiry => Get(nameof(Settings_HubcapKeyOkExpiry));
    public static string Settings_HubcapKeyBad => Get(nameof(Settings_HubcapKeyBad));
    public static string Settings_HubcapKeyError => Get(nameof(Settings_HubcapKeyError));
    public static string Settings_HubcapKeyRejected => Get(nameof(Settings_HubcapKeyRejected));
    public static string Settings_HubcapKeyOffline => Get(nameof(Settings_HubcapKeyOffline));
    public static string Settings_HubcapKeyRateLimited => Get(nameof(Settings_HubcapKeyRateLimited));
    public static string Settings_HubcapExpiryExpired => Get(nameof(Settings_HubcapExpiryExpired));
    public static string Settings_HubcapExpiryToday => Get(nameof(Settings_HubcapExpiryToday));
    public static string Settings_HubcapExpirySoon => Get(nameof(Settings_HubcapExpirySoon));
    public static string Hubcap_Err_KeyRejected => Get(nameof(Hubcap_Err_KeyRejected));
    public static string Hubcap_Err_DailyLimit => Get(nameof(Hubcap_Err_DailyLimit));
    public static string Hubcap_Err_DailyLimitRetry => Get(nameof(Hubcap_Err_DailyLimitRetry));
    public static string Hubcap_Err_NoManifest => Get(nameof(Hubcap_Err_NoManifest));
    public static string Hubcap_Err_Status => Get(nameof(Hubcap_Err_Status));
    public static string Hubcap_Err_Unreachable => Get(nameof(Hubcap_Err_Unreachable));
    public static string Hubcap_Err_Generic => Get(nameof(Hubcap_Err_Generic));
    public static string Hubcap_Wait_Seconds => Get(nameof(Hubcap_Wait_Seconds));
    public static string Hubcap_Wait_Minutes => Get(nameof(Hubcap_Wait_Minutes));
    public static string Hubcap_Wait_Hours => Get(nameof(Hubcap_Wait_Hours));
    public static string Settings_Accent => Get(nameof(Settings_Accent));
    public static string Settings_Accent_Hint => Get(nameof(Settings_Accent_Hint));
    public static string Settings_Accent_Amethyst => Get(nameof(Settings_Accent_Amethyst));
    public static string Settings_Accent_Green => Get(nameof(Settings_Accent_Green));
    public static string Settings_Accent_Red => Get(nameof(Settings_Accent_Red));
    public static string Settings_Accent_Apply => Get(nameof(Settings_Accent_Apply));
    public static string Startup_Title => Get(nameof(Startup_Title));
    public static string Startup_Steam_Closing => Get(nameof(Startup_Steam_Closing));
    public static string Startup_Steam_Closed => Get(nameof(Startup_Steam_Closed));
    public static string Startup_Steam_Stubborn_Title => Get(nameof(Startup_Steam_Stubborn_Title));
    public static string Startup_Steam_Stubborn_Body => Get(nameof(Startup_Steam_Stubborn_Body));
    public static string Startup_Steam_LeftRunning => Get(nameof(Startup_Steam_LeftRunning));
    public static string Startup_Steam_Reopen_Body => Get(nameof(Startup_Steam_Reopen_Body));
    public static string Startup_Steam_Reopen_Action => Get(nameof(Startup_Steam_Reopen_Action));
    public static string Startup_Steam_ReopenFailed => Get(nameof(Startup_Steam_ReopenFailed));
    public static string About_Changelog_Title => Get(nameof(About_Changelog_Title));
    public static string About_Changelog_Show => Get(nameof(About_Changelog_Show));
    public static string About_Changelog_Hide => Get(nameof(About_Changelog_Hide));
    public static string Settings_HubcapActive => Get(nameof(Settings_HubcapActive));
    public static string Settings_HubcapRefresh => Get(nameof(Settings_HubcapRefresh));
    public static string Settings_Language => Get(nameof(Settings_Language));
    public static string Settings_Language_Hint => Get(nameof(Settings_Language_Hint));
    public static string Settings_Language_SystemDefault => Get(nameof(Settings_Language_SystemDefault));
    public static string Settings_SteamLocation => Get(nameof(Settings_SteamLocation));
    public static string Settings_Change => Get(nameof(Settings_Change));
    public static string Settings_Open => Get(nameof(Settings_Open));
    public static string Settings_ResetToAuto => Get(nameof(Settings_ResetToAuto));
    public static string Settings_AutoUpdateApps => Get(nameof(Settings_AutoUpdateApps));
    public static string Settings_AutoUpdateApps_Hint => Get(nameof(Settings_AutoUpdateApps_Hint));
    public static string Settings_Section_Startup => Get(nameof(Settings_Section_Startup));
    public static string Settings_StartWithWindows => Get(nameof(Settings_StartWithWindows));
    public static string Settings_StartWithWindows_Hint => Get(nameof(Settings_StartWithWindows_Hint));
    public static string Settings_MinimizeToTray => Get(nameof(Settings_MinimizeToTray));
    public static string Settings_MinimizeToTray_Hint => Get(nameof(Settings_MinimizeToTray_Hint));
    public static string Tray_Open => Get(nameof(Tray_Open));
    public static string Tray_Exit => Get(nameof(Tray_Exit));
    public static string Settings_SteamNotFound => Get(nameof(Settings_SteamNotFound));
    public static string Settings_SteamSource_Custom => Get(nameof(Settings_SteamSource_Custom));
    public static string Settings_SteamSource_NotFound => Get(nameof(Settings_SteamSource_NotFound));
    public static string Settings_SteamSource_Auto => Get(nameof(Settings_SteamSource_Auto));
    public static string Settings_SteamWarning_NoExe => Get(nameof(Settings_SteamWarning_NoExe));
    public static string Settings_ChooseSteamFolder => Get(nameof(Settings_ChooseSteamFolder));

    // ── Language changed prompt ──
    public static string Lang_Changed_Title => Get(nameof(Lang_Changed_Title));
    public static string Lang_Changed_Body => Get(nameof(Lang_Changed_Body));
    public static string Lang_Changed_Restart => Get(nameof(Lang_Changed_Restart));

    // ── Home ──
    public static string Home_Welcome => Get(nameof(Home_Welcome));
    public static string Home_LuasOnBoard => Get(nameof(Home_LuasOnBoard));
    public static string Home_LastAdded => Get(nameof(Home_LastAdded));
    public static string Home_PluginStatus => Get(nameof(Home_PluginStatus));
    public static string Home_RecentlyAdded => Get(nameof(Home_RecentlyAdded));
    public static string Home_ViewDetails => Get(nameof(Home_ViewDetails));
    public static string Home_CheckingSteam => Get(nameof(Home_CheckingSteam));
    public static string Home_SteamDetected => Get(nameof(Home_SteamDetected));
    public static string Home_SteamNotFound => Get(nameof(Home_SteamNotFound));
    public static string Home_BrowsingAsGuest => Get(nameof(Home_BrowsingAsGuest));
    public static string Home_SignedIn => Get(nameof(Home_SignedIn));
    public static string Home_SignedInAs => Get(nameof(Home_SignedInAs));
    public static string Home_NoModeSelected => Get(nameof(Home_NoModeSelected));
    public static string Home_ModeIs => Get(nameof(Home_ModeIs));

    // ── Mode ──
    public static string Mode_Title => Get(nameof(Mode_Title));
    public static string Mode_Subtitle => Get(nameof(Mode_Subtitle));
    public static string Mode_CheckForUpdates => Get(nameof(Mode_CheckForUpdates));
    public static string Mode_Active => Get(nameof(Mode_Active));
    public static string Mode_Recommended => Get(nameof(Mode_Recommended));
    public static string Mode_Confirm_Body => Get(nameof(Mode_Confirm_Body));
    public static string Mode_Cancel => Get(nameof(Mode_Cancel));
    public static string Mode_CloseSteamContinue => Get(nameof(Mode_CloseSteamContinue));
    public static string Mode_Desc_SteamTools => Get(nameof(Mode_Desc_SteamTools));
    public static string Mode_Desc_OpenSteamTools => Get(nameof(Mode_Desc_OpenSteamTools));
    public static string Mode_Desc_CloudRedirect => Get(nameof(Mode_Desc_CloudRedirect));
    public static string Mode_CloudRedirect_Manage => Get(nameof(Mode_CloudRedirect_Manage));
    public static string Mode_CloudRedirect_LaunchFailed => Get(nameof(Mode_CloudRedirect_LaunchFailed));
    public static string Mode_Desc_OpenSteamToolsNightly => Get(nameof(Mode_Desc_OpenSteamToolsNightly));
    public static string Mode_Experimental => Get(nameof(Mode_Experimental));
    public static string Mode_CloudRedirectSupport => Get(nameof(Mode_CloudRedirectSupport));
    public static string Mode_CloudRedirect_AddonDesc => Get(nameof(Mode_CloudRedirect_AddonDesc));
    public static string Mode_CloudRedirect_Locked => Get(nameof(Mode_CloudRedirect_Locked));
    public static string Mode_CloudRedirect_Enable => Get(nameof(Mode_CloudRedirect_Enable));
    public static string Mode_CloudRedirect_Disable => Get(nameof(Mode_CloudRedirect_Disable));
    public static string Mode_CloudRedirect_Status_Enabled => Get(nameof(Mode_CloudRedirect_Status_Enabled));
    public static string Mode_CloudRedirect_Status_Disabled => Get(nameof(Mode_CloudRedirect_Status_Disabled));
    public static string Mode_CloudRedirect_Status_NotInstalled => Get(nameof(Mode_CloudRedirect_Status_NotInstalled));
    public static string Mode_CloudRedirect_Status_UpdateAvailable => Get(nameof(Mode_CloudRedirect_Status_UpdateAvailable));
    public static string Mode_CloudRedirect_Toast_Enabled => Get(nameof(Mode_CloudRedirect_Toast_Enabled));
    public static string Mode_CloudRedirect_Toast_Disabled => Get(nameof(Mode_CloudRedirect_Toast_Disabled));
    public static string Mode_CloudRedirect_Toast_Updated => Get(nameof(Mode_CloudRedirect_Toast_Updated));
    public static string Onboarding_Title => Get(nameof(Onboarding_Title));
    public static string Onboarding_SignIn_Blurb => Get(nameof(Onboarding_SignIn_Blurb));
    public static string Onboarding_SignedIn => Get(nameof(Onboarding_SignedIn));
    public static string Onboarding_Recommended_Title => Get(nameof(Onboarding_Recommended_Title));
    public static string Onboarding_Recommended_Detail => Get(nameof(Onboarding_Recommended_Detail));
    public static string Onboarding_Plugin_Title => Get(nameof(Onboarding_Plugin_Title));
    public static string Onboarding_Plugin_Detail => Get(nameof(Onboarding_Plugin_Detail));
    public static string Onboarding_Yes => Get(nameof(Onboarding_Yes));
    public static string Onboarding_No => Get(nameof(Onboarding_No));
    public static string Onboarding_Go => Get(nameof(Onboarding_Go));
    public static string Onboarding_Applying => Get(nameof(Onboarding_Applying));
    public static string Mode_Checking => Get(nameof(Mode_Checking));
    public static string Mode_StatusUnavailable => Get(nameof(Mode_StatusUnavailable));
    public static string Mode_NotActive => Get(nameof(Mode_NotActive));
    public static string Mode_NotInstalled => Get(nameof(Mode_NotInstalled));
    public static string Mode_UpToDate => Get(nameof(Mode_UpToDate));
    public static string Mode_UpdateAvailable => Get(nameof(Mode_UpdateAvailable));
    public static string Mode_Btn_Reinstall => Get(nameof(Mode_Btn_Reinstall));
    public static string Mode_Btn_Update => Get(nameof(Mode_Btn_Update));
    public static string Mode_Btn_Install => Get(nameof(Mode_Btn_Install));
    public static string Mode_Btn_Switch => Get(nameof(Mode_Btn_Switch));
    public static string Mode_Btn_Uninstall => Get(nameof(Mode_Btn_Uninstall));
    public static string Mode_Confirm_Uninstall => Get(nameof(Mode_Confirm_Uninstall));
    public static string Mode_Confirm_Uninstall_Body => Get(nameof(Mode_Confirm_Uninstall_Body));
    public static string Mode_Uninstall_NoRecord => Get(nameof(Mode_Uninstall_NoRecord));
    public static string Mode_Toast_Uninstalled => Get(nameof(Mode_Toast_Uninstalled));
    public static string Mode_Confirm_Reinstall => Get(nameof(Mode_Confirm_Reinstall));
    public static string Mode_Confirm_Switch => Get(nameof(Mode_Confirm_Switch));
    public static string Mode_Toast_Updated => Get(nameof(Mode_Toast_Updated));
    public static string Mode_Toast_Updated_Restarting => Get(nameof(Mode_Toast_Updated_Restarting));
    public static string Mode_Toast_Updated_Start => Get(nameof(Mode_Toast_Updated_Start));
    public static string Mode_Toast_InstallFailed => Get(nameof(Mode_Toast_InstallFailed));
    public static string Mode_Toast_InstallFailed_Body => Get(nameof(Mode_Toast_InstallFailed_Body));

    // ── Drop zone ──
    public static string Drop_Title => Get(nameof(Drop_Title));
    public static string Drop_LinkHint => Get(nameof(Drop_LinkHint));
    public static string Drop_BrowseFiles => Get(nameof(Drop_BrowseFiles));
    public static string Drop_Picker_Title => Get(nameof(Drop_Picker_Title));
    public static string Drop_Picker_Filter => Get(nameof(Drop_Picker_Filter));
    public static string Drop_Nothing => Get(nameof(Drop_Nothing));
    public static string Drop_Confirm_Replace => Get(nameof(Drop_Confirm_Replace));
    public static string Drop_Confirm_NoChanges => Get(nameof(Drop_Confirm_NoChanges));
    public static string Drop_NothingInstalled => Get(nameof(Drop_NothingInstalled));
    public static string Drop_Count_Luas => Get(nameof(Drop_Count_Luas));
    public static string Drop_Count_Manifests => Get(nameof(Drop_Count_Manifests));
    public static string Drop_Result_Installed => Get(nameof(Drop_Result_Installed));
    public static string Drop_Result_Failed => Get(nameof(Drop_Result_Failed));
    public static string Drop_Result_RestartApply => Get(nameof(Drop_Result_RestartApply));

    // ── Common ──
    public static string Common_SearchPlaceholder => Get(nameof(Common_SearchPlaceholder));
    public static string Common_Loading => Get(nameof(Common_Loading));
    public static string Common_AppId => Get(nameof(Common_AppId));
    public static string Common_AppFallback => Get(nameof(Common_AppFallback));

    // ── Manage ──
    public static string Manage_Title => Get(nameof(Manage_Title));
    public static string Manage_Refresh => Get(nameof(Manage_Refresh));
    public static string Manage_Filters => Get(nameof(Manage_Filters));
    public static string Manage_Filter_Type => Get(nameof(Manage_Filter_Type));
    public static string Manage_Filter_Genre => Get(nameof(Manage_Filter_Genre));
    public static string Manage_Filter_Year => Get(nameof(Manage_Filter_Year));
    public static string Manage_Filter_Price => Get(nameof(Manage_Filter_Price));
    public static string Manage_Filter_Content => Get(nameof(Manage_Filter_Content));
    public static string Manage_Content_HideAdult => Get(nameof(Manage_Content_HideAdult));
    public static string Manage_Content_AdultOnly => Get(nameof(Manage_Content_AdultOnly));
    public static string Manage_Filter_SortBy => Get(nameof(Manage_Filter_SortBy));
    public static string Manage_ClearFilters => Get(nameof(Manage_ClearFilters));
    public static string Manage_Select => Get(nameof(Manage_Select));
    public static string Manage_DeleteThisLua => Get(nameof(Manage_DeleteThisLua));
    public static string Manage_ResultsPerPage => Get(nameof(Manage_ResultsPerPage));
    public static string Manage_Action_ViewDetails => Get(nameof(Manage_Action_ViewDetails));
    public static string Manage_Action_Update => Get(nameof(Manage_Action_Update));
    public static string Manage_Action_OpenStore => Get(nameof(Manage_Action_OpenStore));
    public static string Manage_Action_OpenInSteam => Get(nameof(Manage_Action_OpenInSteam));
    public static string Manage_Action_Reveal => Get(nameof(Manage_Action_Reveal));
    public static string Manage_Action_CopyAppId => Get(nameof(Manage_Action_CopyAppId));
    public static string Manage_Action_RemoveDrm => Get(nameof(Manage_Action_RemoveDrm));
    public static string Manage_Action_ManageBuild => Get(nameof(Manage_Action_ManageBuild));
    public static string Manage_Action_Play => Get(nameof(Manage_Action_Play));
    public static string Manage_Action_Install => Get(nameof(Manage_Action_Install));
    public static string Manage_Play_Installing_Title => Get(nameof(Manage_Play_Installing_Title));
    public static string Manage_Play_Installing_Body => Get(nameof(Manage_Play_Installing_Body));
    public static string Manage_Play_Failed_Title => Get(nameof(Manage_Play_Failed_Title));
    public static string Manage_Play_Failed_Body => Get(nameof(Manage_Play_Failed_Body));
    public static string Manage_Play_SteamUnavailable_Body => Get(nameof(Manage_Play_SteamUnavailable_Body));
    public static string Manage_AboutHeader => Get(nameof(Manage_AboutHeader));
    public static string Manage_Info_Developer => Get(nameof(Manage_Info_Developer));
    public static string Manage_Info_Publisher => Get(nameof(Manage_Info_Publisher));
    public static string Manage_ActionsHeader => Get(nameof(Manage_ActionsHeader));
    public static string Manage_Steamless_Confirm_Title => Get(nameof(Manage_Steamless_Confirm_Title));
    public static string Manage_Steamless_Confirm_Body => Get(nameof(Manage_Steamless_Confirm_Body));
    public static string Manage_Steamless_Working => Get(nameof(Manage_Steamless_Working));
    public static string Manage_Toast_Steamless_Done => Get(nameof(Manage_Toast_Steamless_Done));
    public static string Manage_Steamless_NoInstall => Get(nameof(Manage_Steamless_NoInstall));
    public static string Manage_Steamless_Failed => Get(nameof(Manage_Steamless_Failed));
    public static string Manage_CopyAppIdTip => Get(nameof(Manage_CopyAppIdTip));
    public static string Manage_LoadingDepotInfo => Get(nameof(Manage_LoadingDepotInfo));
    public static string Manage_MissingHint => Get(nameof(Manage_MissingHint));
    public static string Manage_UnknownHint => Get(nameof(Manage_UnknownHint));
    public static string Manage_Clear => Get(nameof(Manage_Clear));
    public static string Manage_DeleteSelected => Get(nameof(Manage_DeleteSelected));
    public static string Manage_LoadingGames => Get(nameof(Manage_LoadingGames));
    public static string Manage_Opt_Any => Get(nameof(Manage_Opt_Any));
    public static string Manage_Opt_Free => Get(nameof(Manage_Opt_Free));
    public static string Manage_Opt_Paid => Get(nameof(Manage_Opt_Paid));
    public static string Manage_Sort_RecentlyAdded => Get(nameof(Manage_Sort_RecentlyAdded));
    public static string Manage_Sort_NameAZ => Get(nameof(Manage_Sort_NameAZ));
    public static string Manage_Sort_ReleaseNewest => Get(nameof(Manage_Sort_ReleaseNewest));
    public static string Manage_Sort_Metacritic => Get(nameof(Manage_Sort_Metacritic));
    public static string Manage_Sort_MostReviewed => Get(nameof(Manage_Sort_MostReviewed));
    public static string Manage_PageSize_All => Get(nameof(Manage_PageSize_All));
    public static string Manage_PageLabel => Get(nameof(Manage_PageLabel));
    public static string Manage_SelectionLabel => Get(nameof(Manage_SelectionLabel));
    public static string Manage_FetchingDetails => Get(nameof(Manage_FetchingDetails));
    public static string Manage_Empty_NoMatch => Get(nameof(Manage_Empty_NoMatch));
    public static string Manage_Empty_NoLuas => Get(nameof(Manage_Empty_NoLuas));
    public static string Manage_Empty_NoSteam => Get(nameof(Manage_Empty_NoSteam));
    public static string Manage_Toast_NotFound_Title => Get(nameof(Manage_Toast_NotFound_Title));
    public static string Manage_Toast_NotFound_Body => Get(nameof(Manage_Toast_NotFound_Body));
    public static string Manage_Toast_Refreshed_Title => Get(nameof(Manage_Toast_Refreshed_Title));
    public static string Manage_Toast_Refreshed_Body => Get(nameof(Manage_Toast_Refreshed_Body));
    public static string Manage_DepotError => Get(nameof(Manage_DepotError));
    public static string Manage_Toggle_InLua => Get(nameof(Manage_Toggle_InLua));
    public static string Manage_Toggle_Missing => Get(nameof(Manage_Toggle_Missing));
    public static string Manage_Toggle_Unknown => Get(nameof(Manage_Toggle_Unknown));
    public static string Manage_Depot => Get(nameof(Manage_Depot));
    public static string Manage_SharedDepot => Get(nameof(Manage_SharedDepot));
    public static string Manage_DlcName => Get(nameof(Manage_DlcName));
    public static string Manage_Delete_Title => Get(nameof(Manage_Delete_Title));
    public static string Manage_Delete_Body => Get(nameof(Manage_Delete_Body));
    public static string Manage_DeleteMany_Title => Get(nameof(Manage_DeleteMany_Title));
    public static string Manage_DeleteMany_Body => Get(nameof(Manage_DeleteMany_Body));
    public static string Manage_RemoveFailed_Title => Get(nameof(Manage_RemoveFailed_Title));
    public static string Manage_RemoveFailed_File => Get(nameof(Manage_RemoveFailed_File));
    public static string Manage_RemoveFailed_Named => Get(nameof(Manage_RemoveFailed_Named));
    public static string Manage_RemoveFailed_Count => Get(nameof(Manage_RemoveFailed_Count));
    public static string Manage_RestartSteam_Title => Get(nameof(Manage_RestartSteam_Title));
    public static string Manage_RestartSteam_Ask => Get(nameof(Manage_RestartSteam_Ask));
    public static string Manage_RestartSteam_Failed => Get(nameof(Manage_RestartSteam_Failed));

    // ── Fixes ──
    public static string Fixes_Title => Get(nameof(Fixes_Title));
    public static string Fixes_Loading => Get(nameof(Fixes_Loading));
    public static string Fixes_Build => Get(nameof(Fixes_Build));
    public static string Fixes_Manifest => Get(nameof(Fixes_Manifest));
    public static string Fixes_Fix => Get(nameof(Fixes_Fix));
    public static string Fixes_Count => Get(nameof(Fixes_Count));
    public static string Fixes_Err_Load => Get(nameof(Fixes_Err_Load));
    public static string Fixes_Empty_None => Get(nameof(Fixes_Empty_None));
    public static string Fixes_SignIn => Get(nameof(Fixes_SignIn));
    public static string Fixes_SignInRequired => Get(nameof(Fixes_SignInRequired));
    public static string Fixes_Toast_DownloadFailed => Get(nameof(Fixes_Toast_DownloadFailed));
    public static string Fixes_Toast_DownloadFailed_Body => Get(nameof(Fixes_Toast_DownloadFailed_Body));
    public static string Fixes_Toast_InstallFailed => Get(nameof(Fixes_Toast_InstallFailed));
    public static string Fixes_Toast_InstallFailed_Body => Get(nameof(Fixes_Toast_InstallFailed_Body));
    public static string Fixes_Toast_FixInstalled => Get(nameof(Fixes_Toast_FixInstalled));
    public static string Fixes_Toast_FixInstalled_Restarting => Get(nameof(Fixes_Toast_FixInstalled_Restarting));
    public static string Fixes_Toast_FixInstalled_Restart => Get(nameof(Fixes_Toast_FixInstalled_Restart));
    public static string Fixes_Toast_GameNotFound => Get(nameof(Fixes_Toast_GameNotFound));
    public static string Fixes_Toast_GameNotFound_Body => Get(nameof(Fixes_Toast_GameNotFound_Body));
    public static string Fixes_Toast_PartiallyApplied => Get(nameof(Fixes_Toast_PartiallyApplied));
    public static string Fixes_Toast_PartiallyApplied_Body => Get(nameof(Fixes_Toast_PartiallyApplied_Body));
    public static string Fixes_Toast_FixApplied => Get(nameof(Fixes_Toast_FixApplied));
    public static string Fixes_Toast_FixApplied_Body => Get(nameof(Fixes_Toast_FixApplied_Body));
    public static string Fixes_Toast_CouldntApply => Get(nameof(Fixes_Toast_CouldntApply));
    public static string Fixes_Toast_Refreshed_Title => Get(nameof(Fixes_Toast_Refreshed_Title));
    public static string Fixes_Toast_Refreshed_Body => Get(nameof(Fixes_Toast_Refreshed_Body));

    // ── Add / Download ──
    public static string Add_Title => Get(nameof(Add_Title));
    public static string Add_Subtitle => Get(nameof(Add_Subtitle));
    public static string Add_SearchPlaceholder => Get(nameof(Add_SearchPlaceholder));
    public static string Add_Featured_TopSellers => Get(nameof(Add_Featured_TopSellers));
    public static string Add_Featured_NewReleases => Get(nameof(Add_Featured_NewReleases));
    public static string Add_Released => Get(nameof(Add_Released));
    public static string Add_Fetch => Get(nameof(Add_Fetch));
    public static string Add_Checking => Get(nameof(Add_Checking));
    public static string Add_Reveal => Get(nameof(Add_Reveal));
    public static string Add_Supporter => Get(nameof(Add_Supporter));
    public static string Add_Unlimited => Get(nameof(Add_Unlimited));
    public static string Add_RequiresOwnKey => Get(nameof(Add_RequiresOwnKey));
    public static string Add_Discord => Get(nameof(Add_Discord));
    public static string Add_JoinDiscord => Get(nameof(Add_JoinDiscord));
    public static string Add_Download => Get(nameof(Add_Download));
    public static string Add_NeedsHubcapKey => Get(nameof(Add_NeedsHubcapKey));
    public static string Add_NeedsHubcapKey_Tip => Get(nameof(Add_NeedsHubcapKey_Tip));
    public static string Add_Depots => Get(nameof(Add_Depots));
    public static string Add_Available => Get(nameof(Add_Available));
    public static string Add_Missing => Get(nameof(Add_Missing));
    public static string Add_NoKey => Get(nameof(Add_NoKey));
    public static string Add_DownloadLua => Get(nameof(Add_DownloadLua));
    public static string Add_Generating => Get(nameof(Add_Generating));
    public static string Add_DlcHint => Get(nameof(Add_DlcHint));
    public static string Add_AlreadyHaveFiles => Get(nameof(Add_AlreadyHaveFiles));
    public static string Add_SignIn_Dlc => Get(nameof(Add_SignIn_Dlc));
    public static string Add_SignIn_Download => Get(nameof(Add_SignIn_Download));
    public static string Add_Err_BaseGame => Get(nameof(Add_Err_BaseGame));
    public static string Add_Err_Generic => Get(nameof(Add_Err_Generic));
    public static string Add_Err_Download => Get(nameof(Add_Err_Download));
    public static string Add_Err_Generate => Get(nameof(Add_Err_Generate));
    public static string Add_Confirm_Replace => Get(nameof(Add_Confirm_Replace));
    public static string Add_Confirm_NoChanges => Get(nameof(Add_Confirm_NoChanges));
    public static string Add_Status_Cancelled => Get(nameof(Add_Status_Cancelled));
    public static string Add_Status_InstallFailed => Get(nameof(Add_Status_InstallFailed));
    public static string Add_Status_AddedManifests => Get(nameof(Add_Status_AddedManifests));
    public static string Add_Status_AddedFetch => Get(nameof(Add_Status_AddedFetch));
    public static string Add_FastFetch => Get(nameof(Add_FastFetch));
    public static string Add_FastFetch_Hint => Get(nameof(Add_FastFetch_Hint));
    public static string Add_FastFetch_NoSource => Get(nameof(Add_FastFetch_NoSource));
    public static string Add_FastFetch_Via => Get(nameof(Add_FastFetch_Via));

    // ── Confirm overlay ──
    public static string Confirm_OpenSteamDb => Get(nameof(Confirm_OpenSteamDb));
    public static string Confirm_Shared => Get(nameof(Confirm_Shared));
    public static string Confirm_ReviewChanges => Get(nameof(Confirm_ReviewChanges));
    public static string Confirm_Adding => Get(nameof(Confirm_Adding));
    public static string Confirm_Removing => Get(nameof(Confirm_Removing));
    public static string Confirm_Skip => Get(nameof(Confirm_Skip));
    public static string Confirm_Replace => Get(nameof(Confirm_Replace));
        public static string Plugin_Title => Get(nameof(Plugin_Title));
        public static string Plugin_Subtitle => Get(nameof(Plugin_Subtitle));
        public static string Plugin_CardTitle => Get(nameof(Plugin_CardTitle));
        public static string Plugin_Badge_UpdateAvailable => Get(nameof(Plugin_Badge_UpdateAvailable));
        public static string Plugin_Row_InstalledVersion => Get(nameof(Plugin_Row_InstalledVersion));
        public static string Plugin_Row_LatestVersion => Get(nameof(Plugin_Row_LatestVersion));
        public static string Plugin_Row_Frontend => Get(nameof(Plugin_Row_Frontend));
        public static string Plugin_Row_Loader => Get(nameof(Plugin_Row_Loader));
        public static string Plugin_Millennium_Coexisting => Get(nameof(Plugin_Millennium_Coexisting));
        public static string Plugin_Footer => Get(nameof(Plugin_Footer));
        public static string Plugin_About_Header => Get(nameof(Plugin_About_Header));
        public static string Plugin_Feature_StoreButton => Get(nameof(Plugin_Feature_StoreButton));
        public static string Plugin_Feature_AutoUpdate => Get(nameof(Plugin_Feature_AutoUpdate));
        public static string Plugin_Feature_Millennium => Get(nameof(Plugin_Feature_Millennium));
        public static string Plugin_Btn_Install => Get(nameof(Plugin_Btn_Install));
        public static string Plugin_Btn_Update => Get(nameof(Plugin_Btn_Update));
        public static string Plugin_Btn_Reinstall => Get(nameof(Plugin_Btn_Reinstall));
        public static string Plugin_Btn_Uninstall => Get(nameof(Plugin_Btn_Uninstall));
        public static string Plugin_Btn_CheckForUpdates => Get(nameof(Plugin_Btn_CheckForUpdates));
        public static string Plugin_Checking => Get(nameof(Plugin_Checking));
        public static string Plugin_Status_Installed => Get(nameof(Plugin_Status_Installed));
        public static string Plugin_Status_NotInstalled => Get(nameof(Plugin_Status_NotInstalled));
        public static string Plugin_Status_UpToDate => Get(nameof(Plugin_Status_UpToDate));
        public static string Plugin_Status_OutOfDate => Get(nameof(Plugin_Status_OutOfDate));
        public static string Plugin_Version_Unknown => Get(nameof(Plugin_Version_Unknown));
        public static string Plugin_Version_Offline => Get(nameof(Plugin_Version_Offline));
        public static string Plugin_Status_OfflineCheck => Get(nameof(Plugin_Status_OfflineCheck));
        public static string Plugin_Status_Port8080Busy => Get(nameof(Plugin_Status_Port8080Busy));
        public static string Plugin_Confirm_RestartBody => Get(nameof(Plugin_Confirm_RestartBody));
        public static string Plugin_Confirm_RestartCaption => Get(nameof(Plugin_Confirm_RestartCaption));
        public static string Plugin_Toast_Title => Get(nameof(Plugin_Toast_Title));
        public static string Plugin_Toast_Installed => Get(nameof(Plugin_Toast_Installed));
        public static string Plugin_Toast_InstallFailed => Get(nameof(Plugin_Toast_InstallFailed));
        public static string Plugin_Toast_UninstallFailed => Get(nameof(Plugin_Toast_UninstallFailed));
        public static string Plugin_Toast_UpdateAvailable => Get(nameof(Plugin_Toast_UpdateAvailable));
        public static string Plugin_Toast_UpToDate => Get(nameof(Plugin_Toast_UpToDate));
        public static string Plugin_Err_SteamNotFound => Get(nameof(Plugin_Err_SteamNotFound));
        public static string Plugin_Err_GithubUnreachable => Get(nameof(Plugin_Err_GithubUnreachable));
        public static string Plugin_Err_MissingAssets => Get(nameof(Plugin_Err_MissingAssets));
        public static string Plugin_Err_VerifyFailed => Get(nameof(Plugin_Err_VerifyFailed));
        public static string Plugin_Err_NoLuatoolsJs => Get(nameof(Plugin_Err_NoLuatoolsJs));
        public static string Plugin_Err_ArchiveRejected => Get(nameof(Plugin_Err_ArchiveRejected));

    // ── Pre-install download notice (Mode + Plugin) ──
        public static string Download_Notice_Title => Get(nameof(Download_Notice_Title));
        public static string Download_Notice_Body => Get(nameof(Download_Notice_Body));
        public static string Download_Notice_Check_Pinned => Get(nameof(Download_Notice_Check_Pinned));
        public static string Download_Notice_Check_Digest => Get(nameof(Download_Notice_Check_Digest));
        public static string Download_Notice_Check_Archive => Get(nameof(Download_Notice_Check_Archive));
        public static string Download_Notice_Cancel => Get(nameof(Download_Notice_Cancel));
        public static string Download_Notice_Cancelled => Get(nameof(Download_Notice_Cancelled));

    // ── Builds page ──
    // NOT YET TRANSLATED — English-only for now (Get falls back to the English resx for any culture
    // whose Strings.<tag>.resx is missing the key). See Resources/README.md → "Pending translation".
    public static string Builds_Title => Get(nameof(Builds_Title));
    public static string Builds_Subtitle => Get(nameof(Builds_Subtitle));
    public static string Builds_NoSelection => Get(nameof(Builds_NoSelection));
    public static string Builds_ActiveBuild => Get(nameof(Builds_ActiveBuild));
    public static string Builds_Active => Get(nameof(Builds_Active));
    public static string Builds_Variant_Default => Get(nameof(Builds_Variant_Default));
    public static string Builds_Variant_Build => Get(nameof(Builds_Variant_Build));
    public static string Builds_Variant_Preset => Get(nameof(Builds_Variant_Preset));
    public static string Builds_Pinned => Get(nameof(Builds_Pinned));
    public static string Builds_AutoUpdating => Get(nameof(Builds_AutoUpdating));
    public static string Builds_LatestBuild => Get(nameof(Builds_LatestBuild));
    public static string Builds_Manifest => Get(nameof(Builds_Manifest));
    public static string Builds_ManifestLatest => Get(nameof(Builds_ManifestLatest));
    public static string Builds_PinDisabled => Get(nameof(Builds_PinDisabled));
    public static string Builds_Meta_Depots => Get(nameof(Builds_Meta_Depots));
    public static string Builds_Meta_Unsaved => Get(nameof(Builds_Meta_Unsaved));
    public static string Builds_Source => Get(nameof(Builds_Source));
    public static string Builds_Action_Apply => Get(nameof(Builds_Action_Apply));
    public static string Builds_Action_Rename => Get(nameof(Builds_Action_Rename));
    public static string Builds_Action_Edit => Get(nameof(Builds_Action_Edit));
    public static string Builds_Action_Delete => Get(nameof(Builds_Action_Delete));
    public static string Builds_Action_Save => Get(nameof(Builds_Action_Save));
    public static string Builds_Action_SaveAsPreset => Get(nameof(Builds_Action_SaveAsPreset));
    public static string Builds_Action_Cancel => Get(nameof(Builds_Action_Cancel));
    public static string Builds_RenamePlaceholder => Get(nameof(Builds_RenamePlaceholder));
    public static string Builds_Editor_Title => Get(nameof(Builds_Editor_Title));
    public static string Builds_Delete_Title => Get(nameof(Builds_Delete_Title));
    public static string Builds_Delete_Body => Get(nameof(Builds_Delete_Body));
    public static string Builds_Delete_ActiveTip => Get(nameof(Builds_Delete_ActiveTip));
    public static string Builds_RemoveGame => Get(nameof(Builds_RemoveGame));
    public static string Builds_RemoveGame_Tip => Get(nameof(Builds_RemoveGame_Tip));
    public static string Builds_RemoveGame_Title => Get(nameof(Builds_RemoveGame_Title));
    public static string Builds_RemoveGame_Body => Get(nameof(Builds_RemoveGame_Body));
    public static string Builds_RemoveGame_Done => Get(nameof(Builds_RemoveGame_Done));
    public static string Builds_RemoveGame_Gone => Get(nameof(Builds_RemoveGame_Gone));
    public static string Builds_RemoveGame_Failed => Get(nameof(Builds_RemoveGame_Failed));
    public static string Builds_Apply_Done => Get(nameof(Builds_Apply_Done));
    public static string Builds_Apply_Failed => Get(nameof(Builds_Apply_Failed));
    public static string Builds_Save_Done => Get(nameof(Builds_Save_Done));
    public static string Builds_Save_Failed => Get(nameof(Builds_Save_Failed));
    public static string Builds_Preset_Saved => Get(nameof(Builds_Preset_Saved));
    public static string Builds_Action_SaveTo => Get(nameof(Builds_Action_SaveTo));
    public static string Builds_Action_SaveAsNew => Get(nameof(Builds_Action_SaveAsNew));
    public static string Builds_Save_Updated => Get(nameof(Builds_Save_Updated));
    public static string Builds_Depot_Lock => Get(nameof(Builds_Depot_Lock));
    public static string Builds_Depot_LockTip => Get(nameof(Builds_Depot_LockTip));
    public static string Builds_Depot_EnableTip => Get(nameof(Builds_Depot_EnableTip));
    public static string Builds_Depot_Search => Get(nameof(Builds_Depot_Search));
    public static string Builds_Depot_NoMatch => Get(nameof(Builds_Depot_NoMatch));
    public static string Builds_Depot_InactiveNote => Get(nameof(Builds_Depot_InactiveNote));

    // ── Launch options ── (English-only for now)
    public static string Manage_Action_LaunchOptions => Get(nameof(Manage_Action_LaunchOptions));
    public static string Launch_Title => Get(nameof(Launch_Title));
    public static string Launch_Loading => Get(nameof(Launch_Loading));
    public static string Launch_NotFound => Get(nameof(Launch_NotFound));
    public static string Launch_UnsupportedFormat => Get(nameof(Launch_UnsupportedFormat));
    public static string Launch_ReadFailed => Get(nameof(Launch_ReadFailed));
    public static string Launch_ExecutableRequired => Get(nameof(Launch_ExecutableRequired));
    public static string Launch_Add => Get(nameof(Launch_Add));
    public static string Launch_Delete => Get(nameof(Launch_Delete));
    public static string Launch_Field_Executable => Get(nameof(Launch_Field_Executable));
    public static string Launch_Field_Arguments => Get(nameof(Launch_Field_Arguments));
    public static string Launch_Field_WorkingDir => Get(nameof(Launch_Field_WorkingDir));
    public static string Launch_Field_Description => Get(nameof(Launch_Field_Description));
    public static string Launch_Field_Os => Get(nameof(Launch_Field_Os));
    public static string Launch_Field_Type => Get(nameof(Launch_Field_Type));
    public static string Launch_Field_BetaKey => Get(nameof(Launch_Field_BetaKey));
    public static string Launch_Field_BetaKey_Tip => Get(nameof(Launch_Field_BetaKey_Tip));
    public static string Launch_Field_OwnsDlc => Get(nameof(Launch_Field_OwnsDlc));
    public static string Launch_InstallPath => Get(nameof(Launch_InstallPath));
    public static string Launch_SteamRestartNote => Get(nameof(Launch_SteamRestartNote));
    public static string Launch_Restore => Get(nameof(Launch_Restore));
    public static string Launch_Restore_Tip => Get(nameof(Launch_Restore_Tip));
    public static string Launch_Restore_Title => Get(nameof(Launch_Restore_Title));
    public static string Launch_Restore_Body => Get(nameof(Launch_Restore_Body));
    public static string Launch_NothingToRestore => Get(nameof(Launch_NothingToRestore));
    public static string Launch_ApplyNow_Title => Get(nameof(Launch_ApplyNow_Title));
    public static string Launch_ApplyNow_Body => Get(nameof(Launch_ApplyNow_Body));
    public static string Launch_Staged => Get(nameof(Launch_Staged));
    public static string Launch_Applied => Get(nameof(Launch_Applied));
    public static string Launch_Applied_Restarted => Get(nameof(Launch_Applied_Restarted));
    public static string Launch_ApplyFailed => Get(nameof(Launch_ApplyFailed));
    public static string Launch_Drift_Title => Get(nameof(Launch_Drift_Title));
    public static string Launch_Drift_Body => Get(nameof(Launch_Drift_Body));
    public static string Launch_Drift_Action => Get(nameof(Launch_Drift_Action));

    // ── Auth errors ──
    // These replace hardcoded English literals that used to be thrown from AuthService. They are listed in
    // check-i18n.py's PENDING_TRANSLATION until the translation pass picks them up.
    public static string Auth_Err_SignInTimedOut => Get(nameof(Auth_Err_SignInTimedOut));
    public static string Auth_Err_CallbackPortBusy => Get(nameof(Auth_Err_CallbackPortBusy));

    // ── Protocol handler consent ──
    public static string Protocol_SilentInstall_Title => Get(nameof(Protocol_SilentInstall_Title));
    public static string Protocol_SilentInstall_Body => Get(nameof(Protocol_SilentInstall_Body));

    // ── CDP (Steam debug bridge) consent ──
    public static string Cdp_Consent_Title => Get(nameof(Cdp_Consent_Title));
    public static string Cdp_Consent_Body => Get(nameof(Cdp_Consent_Body));

    // ── Privacy notice for the one remaining cleartext call (see AppConfig.ManifestBackendUrl) ──
    public static string Privacy_HttpMetadata_Title => Get(nameof(Privacy_HttpMetadata_Title));
    public static string Privacy_HttpMetadata_Body => Get(nameof(Privacy_HttpMetadata_Body));

    // ── Theme guard (fires if a WPF-UI upgrade breaks the accent override) ──
    public static string Theme_Guard_Title => Get(nameof(Theme_Guard_Title));
    public static string Theme_Guard_Body => Get(nameof(Theme_Guard_Body));

    // ── Product identity ──
    public static string App_DisplayName => Get(nameof(App_DisplayName));

    // ── Build identity guard ──
    public static string Build_NotFork_Title => Get(nameof(Build_NotFork_Title));
    public static string Build_NotFork_Body => Get(nameof(Build_NotFork_Body));

    // ── Fix/manifest safety screening (FixAnalyzer) ──
    public static string Fixes_Toast_Blocked => Get(nameof(Fixes_Toast_Blocked));
    public static string Fixes_Toast_Blocked_Body => Get(nameof(Fixes_Toast_Blocked_Body));

    // ── About page ──
    public static string About_Nav => Get(nameof(About_Nav));
    public static string About_Title => Get(nameof(About_Title));
    public static string About_What_Header => Get(nameof(About_What_Header));
    public static string About_What_Body => Get(nameof(About_What_Body));
    public static string About_Version_Header => Get(nameof(About_Version_Header));
    public static string About_Repo_Header => Get(nameof(About_Repo_Header));
    public static string About_Updates_Header => Get(nameof(About_Updates_Header));
    public static string About_Updates_Enabled => Get(nameof(About_Updates_Enabled));
    public static string About_Updates_Disabled => Get(nameof(About_Updates_Disabled));
    public static string About_Updates_Sources => Get(nameof(About_Updates_Sources));
    public static string About_Check_Button => Get(nameof(About_Check_Button));
    public static string About_Check_Checking => Get(nameof(About_Check_Checking));
    public static string About_Check_UpToDate => Get(nameof(About_Check_UpToDate));
    public static string About_Check_Found => Get(nameof(About_Check_Found));
    public static string About_Check_Failed => Get(nameof(About_Check_Failed));
    public static string About_Check_Disabled => Get(nameof(About_Check_Disabled));
    public static string About_OpenRepo => Get(nameof(About_OpenRepo));
    public static string About_OpenSettings => Get(nameof(About_OpenSettings));
    public static string About_Config_Header => Get(nameof(About_Config_Header));
    public static string About_Config_Body => Get(nameof(About_Config_Body));

    // ── AmethystTool card (Mode page) ──
    public static string Amethyst_CardTitle => Get(nameof(Amethyst_CardTitle));
    public static string Amethyst_Description => Get(nameof(Amethyst_Description));
    public static string Amethyst_Row_Payload => Get(nameof(Amethyst_Row_Payload));
    public static string Amethyst_Toast_Installed => Get(nameof(Amethyst_Toast_Installed));
    public static string Amethyst_Toast_Failed => Get(nameof(Amethyst_Toast_Failed));
    public static string Amethyst_Err_MissingAsset => Get(nameof(Amethyst_Err_MissingAsset));
    public static string Amethyst_Err_Archive => Get(nameof(Amethyst_Err_Archive));
    public static string Amethyst_Backup_Line => Get(nameof(Amethyst_Backup_Line));

    // ── Plugin removal (uninstall) ──
    public static string Removal_Confirm_Caption => Get(nameof(Removal_Confirm_Caption));
    public static string Removal_Confirm_Body => Get(nameof(Removal_Confirm_Body));
    public static string Removal_Toast_Removed => Get(nameof(Removal_Toast_Removed));
    public static string Removal_Toast_RemovedSteamStopped => Get(nameof(Removal_Toast_RemovedSteamStopped));
    public static string Removal_Toast_NothingToDo => Get(nameof(Removal_Toast_NothingToDo));
    public static string Removal_Toast_NoRecord => Get(nameof(Removal_Toast_NoRecord));
    public static string Removal_Toast_SharedKept => Get(nameof(Removal_Toast_SharedKept));
    public static string Removal_Toast_Failed => Get(nameof(Removal_Toast_Failed));
    public static string Removal_Err_Record => Get(nameof(Removal_Err_Record));
}
